### Create User

POST http://localhost:8080/users
Content-Type: application/json

{
"username": "johGS2n_doe",
"password": "12345678"
}

### Get All Users

GET http://localhost:8080/users

### Get All Users (Paging)

GET http://localhost:8080/users?page=0&size=5

### Get User By ID

GET http://localhost:8080/users/1

### Delete User

DELETE http://localhost:8080/users/1

### Trigger Validation Error

POST http://localhost:8080/users
Content-Type: application/

