#Spring Boot application properties
spring.application.name=contactmanager
spring.profiles.active=docker
logging.level.root=INFO
logging.level.com.example.contactmanager=DEBUG

# use H2 in-memory database for tests ? no real DB needed
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# JWT configuration
jwt.secret=your-super-secure-long-secret-key
jwt.expiration=3600000