spring.application.name=contactmanager
spring.profiles.active=docker
logging.level.root=INFO
logging.level.com.example.contactmanager=DEBUG

jwt.secret=your-super-secure-long-secret-key
jwt.expiration=3600000